name: perfectshelter # DO NOT CHANGE THIS
description: Welcome to Perfectshelter.

publish_to: 'none'
version: 1.2.5+64

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core UI & Charts
  carousel_slider: ^5.0.0
  custom_refresh_indicator: ^4.0.1
  dotted_border: ^3.0.1
  flutter_html: ^3.0.0-beta.1
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  nested: ^1.0.0

  # Firebase Services
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  # Authentication & Sign-in
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # Media & Visuals
  cached_network_image: ^3.4.1
  flick_video_player: ^0.9.0
  flutter_image_compress: ^2.3.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  panorama_viewer: ^2.0.4
  video_player: ^2.9.2
  youtube_explode_dart: any
  youtube_player_flutter: ^9.1.1

  # Audio
  just_audio: ^0.10.0
  record: ^6.0.0

  # Animations
  lottie: ^3.3.1
  shimmer: ^3.0.0

  # Networking & HTTP
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  http: ^1.0.0
  http_parser: any

  # State Management & Storage
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

  # Location & Maps
  geocoding: ^4.0.0
  geolocator: ^14.0.0
  google_maps_flutter: ^2.8.0
  webview_flutter: ^4.11.0

  # Pickers & Input
  country_picker: ^2.0.26
  file_picker: ^10.2.0
  sms_autofill: ^2.4.0

  # Utilities & Tools
  device_info_plus: ^11.3.3
  encrypt: ^5.0.3
  fluttertoast: ^8.2.8
  intl: ^0.20.0
  open_filex: ^4.6.0
  package_info_plus: ^8.0.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  printing: ^5.14.2
  share_plus: ^11.0.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  very_good_analysis: ^9.0.0
  pointycastle: ^3.6.2
  
  # Payment Gateways
  flutter_stripe: ^11.2.0
  in_app_purchase: ^3.2.0
  razorpay_flutter: ^1.3.7

  # Notifications & Reviews
  awesome_notifications: ^0.10.1
  google_mobile_ads: ^6.0.0
  in_app_review: ^2.0.10

  # PDF Generation
  flutter_html_to_pdf: ^0.7.0

  # Moved from dependencies_overrides
  web: ^1.0.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icons/ic_launcher.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/app_icons/
    - assets/languages/
    - assets/lottie/
    - assets/chat_background/
    - assets/svg/MultiColorSvg/
    - assets/svg/social_media/
    - assets/svg/Fallback/
    - assets/city.jpg
    - assets/map.png
    - assets/location_rent.png
    - assets/location_sell.png
    - assets/location_selected.png
    - assets/login_background.png
    - assets/map_styles/

  fonts:
    - family: PrimaryFont 
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800